<div class="container">
	<ol class="breadcrumb">
		<li><a href="<?php echo $this->url('reserva')?>">Reservas</a></li>
		<li class="active">Generar Reserva</li>
	</ol>
	<h3><?php echo $this->translate('Agregar Reserva'); ?></h3>

    <form id="formulario" action="<?php $this->url('reserva', array('action' => 'add')); ?>" method="post">
        <input type="hidden" name="cliente" id="cliente" value="" />
        <input type="hidden" name="idsHabitaciones" id="idsHabitaciones" value="" />
        <div class="row">
            <label><span>Fecha de Ingreso</span>
                <input type="date" name="arrival" id="arrival" value="<?php echo date('Y-m-d');?>" />
            </label>
        </div>
        <div class="row">
            <label><span>Fecha de Egreso</span>
                <input type="date" name="departure" id="departure" value="<?php echo date('Y-m-d');?>" />
            </label>
        </div>
        <div class="row">
            <label><span>Cantidad de Huespedes</span>
                <input type="text" name="cantidadHuespedes" id="cantidadHuespedes" value="0" />
            </label>
        </div>
        <div class="row">
            <label><span>Cantidad de Menores</span>
            <input type="text" name="cantidadMenores" id="cantidadMenores" value="0" />
            </label>
        </div>
        <div class="row">
            <label><span>Cantidad de Huespedes por Habitacion</span>
            <input type="text" name="cantidadHuespHab" id="cantidadHuespHab" value="0" />
            </label>
        </div>
        <script type="text/javascript">
            $('#formulario').on('change', function() {

                var baseUrl = "<?php echo $this->url('findreserva'); ?>";
                var finalUrl = baseUrl + '/'
                                + (parseInt($('#cantidadHuespedes').val()) + parseInt($('#cantidadMenores').val()))
                                    .toString() + '/'
                                + parseInt($('#cantidadHuespHab').val()).toString() + '/'
                                + $('#arrival').val() + '/' + $('#departure').val();
                $.ajax(finalUrl, {
                    beforeSend: function () {
                        $('#habitaciones').html('<span class="spinner"><i class="glyphicon glyphicon-refresh"></i></span>');
                        $('#habitaciones').addClass('active');
                    },
                    success: function (html) {
                        $('#habitaciones').html(html);
                        $('#habitaciones').removeClass('active');
                    }
                });
})
                </script>
        <div class="row">
            <label><span>Cliente</span>
                <input type="text" name="cliente" id="clienteAutocomplete" />
            </label>
            <script type="text/javascript">
$('#clienteAutocomplete').autocomplete({
    autoFocus: true,
    source: function(request, response) {
        $.get('/contabilidad?page=nueva_venta&tipo=factura', { buscar_cliente: request.term }, function(data) {
            var res = [];
            if(data.suggestions) {
                for(var i in data.suggestions) {
                    var result = data.suggestions[i];
                    res.push({
                        label: result.value,
                        value: result.data
                    });
                }
            }
            response(res);
        })
    },
    minLength: 3,
    response: autocomplete_response,
    select: autcomplete_select,
    focus: autocomplete_focus
});
            </script>
        </div>
        <div id="clientInfo" class="has-spinner">
            <p><span class="spinner"><i class="glyphicon glyphicon-refresh"></i></span></p>
        </div>
        <h2>Habitaciones Disponibles:</h2>
        <div id="habitaciones" class="has-spinner">

        </div>
        <h2>Tarifa:</h2>
        <div id="tarfa" class="has-spinner">

        </div>

        <div class="row">
            <input type="submit" value="Reservar" />
        </div>
    </form>

    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <form action>
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Agregar Cliente</h4>
                </div>
                <div class="modal-body">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>
                </form>
            </div>
        </div>
    </div>
</div>