<div class="container">
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('reserva', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form) ?>
	<ol class="breadcrumb">
		<li><a href="<?php echo $this->url('home')?>reserva/index">Reservas</a></li>
		<li class="active">Generar Reserva</li>
	</ol>
	<h3><?php echo $this->translate('Agregar Reserva'); ?></h3>
	<?php
	echo $this->formCollection($this->form); ?>
	<div class="row">
		<div class="col-sm-2">
			<a href="" class="btn btn-info">Imprimir</a>
		</div>
		<div class="col-sm-2">
			<a href="" class="btn btn-info">Check Out</a>
		</div>
		<div class="col-sm-2">
			<a href="" class="btn btn-info">Generar Pago</a>
		</div>




	</div>

</div>

<br><br><br>
<div class="row">






</div>

</div>

<?php  echo $this->form()->closeTag() ?>

<script type="text/javascript">

	$(document).ready(function(){
		$('#agregarHuesped').on('click', function()
		{
			var nombre= $('#nombreHuesped').val();
			var documento= $('#documentoHuesped').val();
			if(nombre==='' || documento==='')
			{
				alert('Complete Nombre y Documento del Huesped');
				return false;
			}else
			{

				var huesped = '<div onclick="remover()" class="huesped">' + nombre + ' - ' +  documento + ' ' + '<a type="button" id="botonHuesped" class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-remove-sign"></span></a></div>' + '<br><br>';
				$('#listaHuesped').append(huesped);
			}
		});

	});


	function remover()
	{
		var huesped = $('.huesped');
		var padre= $(this).parent();
		huesped.remove();

	}

</script>
