<script type="text/javascript">

$(document).ready(function()
	{
		$('#totalReserva').val('holaaa');

	});


</script>
<div class="container">
	<?php
		$form = $this->form;
		$form->setAttribute('action', 
							$this->url('reserva', array('action' => 'book', 'id' => $this->idHabitacione))
							);
    	$form->prepare();
		$formLabel = $this->plugin('formLabel');
		echo $this->form()->openTag($form);
	?>

	<br>
	<ol class="breadcrumb">
  		<li><a href="<?php echo $this->url('home')?>reserva/index">Reservas</a></li>
  		<li class="active">Generar Reserva</li>  		
	</ol>
	<h3><?php echo $this->titulo ?></h3>	
	
	<div class="row">
		<h4>Reservas</h4><hr>
		<div class="col-sm-2">
			<?php
    			$numeroHabitacion = $form->get('numeroHabitacion');
    			$numeroHabitacion->setValue($habitacion->numero);     			
    			echo $formLabel->openTag() . $numeroHabitacion->getLabel('label');    			
    			echo $this->formElementErrors($numeroHabitacion);
    			echo $formLabel->closeTag();
    			echo $this->formInput($numeroHabitacion);
			?>
		</div>
		<?php 
			$idHabitacion=$form->get('idHabitacion');
			$idHabitacion->setValue($habitacion->idHabitacion);
			echo $this->formHidden($idHabitacion); 
                        
                        $idCliente=$form->get('idCliente');			
			echo $this->formHidden($idCliente); 
			 
		?>
		<div class="col-sm-2">
			<?php
    			$pabellon = $form->get('pabellon');   				 
    			$pabellon->setValue($pabellonEncontrado->nombre); 
    			echo $formLabel->openTag() . $pabellon->getLabel('label');    			
    			echo $this->formElementErrors($pabellon);
    			echo $formLabel->closeTag();
    			echo $this->formInput($pabellon);
			?>
		</div>
		<div class="col-sm-2">
			<?php
    			$fechaIngreso = $form->get('fechaIngreso');
    			echo $formLabel->openTag() . $fechaIngreso->getLabel('label');    			
    			echo $formLabel->closeTag();
    			echo $this->formInput($fechaIngreso);
    			?>
    			<div style="color:red">
    			<?php echo $this->formElementErrors($fechaIngreso);?>
		        </div>
		</div>        
		<div class="col-sm-2">
			<?php
    			$fechaSalida = $form->get('fechaSalida');
    			echo $formLabel->openTag() . $fechaSalida->getLabel('label');    			    			
    			echo $formLabel->closeTag();
    			echo $this->formInput($fechaSalida);
    			?>
    			<div style="color:red">
    				<?php echo $this->formElementErrors($fechaSalida);?>
    			</div>
		</div>	

		
	</div><br>
	<div class="row">
		
		<div class="col-sm-6">
			<?php
    			//$nombreReserva = $form->get('nombreReserva');
    			//echo $formLabel->openTag() . $nombreReserva->getLabel('label');    			
    			//echo $this->formElementErrors($nombreReserva);
    			//echo $formLabel->closeTag();
    			//echo $this->formInput($nombreReserva);
			?>
                    

                        <?php 
                        $autocomplete=$form->get('autocomplete');
                        echo $formLabel->openTag() . $autocomplete->getLabel('label');    			
                        echo $formLabel->closeTag();
                        echo $this->formJqueryAutocomplete($autocomplete); 
                        
                        ?>

		</div>
		<div class="col-sm-2">
			<?php
    			$idEstado = $form->get('idEstado');
    			echo $formLabel->openTag() . $idEstado->getLabel('label');    			
    			echo $this->formElementErrors($idEstado);
    			echo $formLabel->closeTag();
    			echo $this->formSelect($idEstado);
			?>
		</div>
	</div>
	<div class="row"><br>	
		<div class="col-sm-3">
			<?php
    			$telefono = $form->get('telefono');
    			echo $formLabel->openTag() . $telefono->getLabel('label');    			
    			echo $this->formElementErrors($telefono);
    			echo $formLabel->closeTag();
    			echo $this->formInput($telefono);
			?>
		</div>
		<div class="col-sm-3">
			<?php
    			$email = $form->get('email');
    			echo $formLabel->openTag() . $email->getLabel('label');    			    			
    			echo $formLabel->closeTag();
    			echo $this->formInput($email);
    			echo $this->formElementErrors($email);
			?>  			
		</div>
		<div class="col-sm-3">
			<?php
    			$idTipoHuesped = $form->get('idTipoHuesped');
    			echo $formLabel->openTag() . $idTipoHuesped->getLabel('label');    			    			
    			echo $formLabel->closeTag();
    			echo $this->formSelect($idTipoHuesped);
    			echo $this->formElementErrors($idTipoHuesped);
			?>  			
		</div>
		<div class="col-sm-3">
			<div class="checkbox"><br>
			<?php
    			$titular = $form->get('titular');
    			echo $formLabel->openTag() . $titular->getLabel('label');    			
    			echo $this->formElementErrors($titular);
    			echo $formLabel->closeTag();
    			echo $this->formCheckbox($titular);
			?>
			</div>
		</div>
	</div>
	<br>
	
	<div class="row">
		
		<div class="col-sm-2">
			<?php
    			$cantidadAdulto = $form->get('cantidadAdulto');
    			echo $formLabel->openTag() . $cantidadAdulto->getLabel('label');    			
    			
    			echo $formLabel->closeTag();
    			echo $this->formInput($cantidadAdulto);
    			?>
    			<div style="color:red">
    			<?php echo $this->formElementErrors($cantidadAdulto); ?>
    			</div>
		</div>
		<div class="col-sm-2">
			<?php
    			$cantidadMenor = $form->get('cantidadMenor');
    			echo $formLabel->openTag() . $cantidadMenor->getLabel('label');    			    			
    			echo $formLabel->closeTag();
    			echo $this->formInput($cantidadMenor);
    			echo $this->formElementErrors($cantidadMenor);
			?>  			
		</div>		
	</div>
	<br><br>
        <h4>Lista de Huespedes</h4><hr>
	<div class="row">
		
		<div class="col-sm-3">

                    <?php
                        $nombreHuesped = $form->get('nombreHuesped');
                        echo $formLabel->openTag() . $nombreHuesped->getLabel('label');    			    			
                        echo $formLabel->closeTag();
                        echo $this->formInput($nombreHuesped);
    			echo $this->formElementErrors($nombreHuesped);
                    ?>			

		</div>
		<div class="col-sm-2">
			<?php
                        $documentoHuesped = $form->get('documentoHuesped');
                        echo $formLabel->openTag() . $documentoHuesped->getLabel('label');    			    			
                        echo $formLabel->closeTag();
                        echo $this->formInput($documentoHuesped);
    			echo $this->formElementErrors($documentoHuesped);
			?>  			
		</div>		
		<div class="col-sm-2">  
                    
		<br>
			<a id="agregarHuesped" class="btn btn-info">Agregar Huesped</a>
		</div>
		<div class="col-sm-2">  
                    <div id="listaHuesped">
                        
                    </div>
		</div>

	</div><br><br>
	
	<h4>Comentarios</h4><hr>
	<div class="row">	
		
		<div class="col-sm-6">
			<?php
    			$comentario = $form->get('comentario');
    			echo $formLabel->openTag() . $comentario->getLabel('label');    			    			
    			echo $formLabel->closeTag();
    			echo $this->formTextArea($comentario);
    			echo $this->formElementErrors($comentario);
			?>  			
		</div>
		

	</div><br><br>
	<h4>Totales</h4><hr>
	
	<div class="row">


		<div class="col-sm-3">
			<?php
    			$totalReserva = $form->get('totalReserva');
    			echo $formLabel->openTag() . $totalReserva->getLabel('label'); 
    			echo $formLabel->closeTag();
    		?>
			<div class="input-group">
    			<span class="input-group-addon">$</span>	
    			<?php
    				echo $this->formInput($totalReserva);
    				echo $this->formElementErrors($totalReserva);
				?>  
			</div>				
		</div>
		<div class="col-sm-3">
			<?php
    			$descuento = $form->get('descuento');
    			echo $formLabel->openTag() . $descuento->getLabel('label');
    			echo $formLabel->closeTag();
    		?>
			<div class="input-group">
    			<span class="input-group-addon">%</span>	
    			<?php	    			    			
    				
    				echo $this->formInput($descuento);
    				echo $this->formElementErrors($descuento);
				?>
			</div>	  			
		</div>
	</div><br>	
	<div class="row">
		<div class="col-sm-6">			
			<?php
    			$total = $form->get('total');
    			echo $formLabel->openTag() . $total->getLabel('label');    			    			
    			echo $formLabel->closeTag();
    		?>
    		<div class="input-group">
    			<span class="input-group-addon">$</span>
    			<?php
    				echo $this->formInput($total);
    				echo $this->formElementErrors($total);
				?>
			</div>  			
		</div>
	</div><br><br>
	<div class="row">
		<div class="col-sm-2">
			<?php echo $this->formElement($form->get('grabarReserva')) ?> 
		</div>	
		<div class="col-sm-2">
			<a href="" class="btn btn-info">Imprimir</a>
		</div>
		<div class="col-sm-2">
			<a href="" class="btn btn-info">Check Out</a>
		</div>
		<div class="col-sm-2">
			<a href="" class="btn btn-info">Generar Pago</a>
		</div>

			
			
			
		</div>		

	</div>	

	<br><br><br>	
	<div class="row">
		
			
			



	</div>

</div>





<?php  echo $this->form()->closeTag() ?>

<script type="text/javascript">

    $(document).ready(function(){
       $('#agregarHuesped').on('click', function()
       {
           var nombre= $('#nombreHuesped').val();
           var documento= $('#documentoHuesped').val();
           if(nombre==='' || documento==='')
           {
               alert('Complete Nombre y Documento del Huesped');
               return false;               
           }else
           {
               
               var huesped = '<div onclick="remover()" class="huesped">' + nombre + ' - ' +  documento + ' ' + '<a type="button" id="botonHuesped" class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-remove-sign"></span></a></div>' + '<br><br>';
               $('#listaHuesped').append(huesped);
           }           
       });
       
    });
    
    
    function remover()
    {
        var huesped = $('.huesped');
        var padre= $(this).parent();
        huesped.remove();
        
    }
    
</script>
