
<div class="container">
	<?php
		$form = $this->form;
		$form->setAttribute('action', $this->url('reserva', array('action' => 'addtarifa')));
    	$form->prepare();
		$formLabel = $this->plugin('formLabel');
		echo $this->form()->openTag($form);
	?>

	<br>
	<ol class="breadcrumb">
    	<li><a href="<?php echo $this->url('home')?>reserva/indextarifa">Tarifa</a></li>
  		<li class="active">Alta</li>
	</ol>
	<h3><?php echo $this->titulo ?></h3>	
	<br>
	<div class="row">
                <?php echo $this->formHidden($form->get('idTarifa')); ?>
		<div class="col-sm-3"><?php
		    $categoria = $form->get('idCategoria');
		    echo $formLabel->openTag() . $categoria->getLabel('label') . $formLabel->closeTag();
		    echo $this->formElement($categoria);
                    ?>
    			<div style="color:red">
    			    <?php echo $this->formElementErrors($categoria);?>	
    			</div>
		</div>

		<div class="col-sm-3"><?php
			$tipoHuesped = $form->get('idTipoHuesped');
			echo $formLabel->openTag() . $tipoHuesped->getLabel('label') . $formLabel->closeTag();
        		echo $this->formElement($tipoHuesped);
                        ?>
    			<div style="color:red">
    			    <?php echo $this->formElementErrors($tipoHuesped);?>
    			</div>
		</div>
		<div class="col-sm-3"><?php
			$monto = $form->get('monto');
			echo $formLabel->openTag() . $monto->getLabel('label') . $formLabel->closeTag();
		        echo $this->formElement($monto);
                        ?>
    			<div style="color:red">
    			    <?php echo $this->formElementErrors($monto);?>
    			</div>
		</div>
		<div class="col-sm-3"><?php
			$vigencia = $form->get('vigencia');
			echo $formLabel->openTag() . $vigencia->getLabel('label') . $formLabel->closeTag();
		        echo $this->formElement($vigencia);
                        ?>
    			<div style="color:red">
    			    <?php echo $this->formElementErrors($vigencia);?>
    			</div>                       
		</div>
	</div>
        <br>
	<div class="row">
		<div class="col-sm-12">
			<?php echo $this->formElement($form->get('send')) ?> 
		</div>		
	</div>
</div>
<?php  echo $this->form()->closeTag() ?>
