<div class="container">
	<?php
		$form = $this->form;
		$form->setAttribute('action', $this->url('reserva', array('action' => 'addpabellon')));
    	$form->prepare();
		$formLabel = $this->plugin('formLabel');
		echo $this->form()->openTag($form);
	?>

	<br>
	<ol class="breadcrumb">
  		<li><a href="<?php echo $this->url('home')?>reserva/indexpabellon">Pabellones</a></li>
  		<li class="active">Edicion</li>  		
	</ol>
	<h3><?php echo $this->titulo ?></h3>	
	<br>	
	<div class="row">
		<?php echo $this->formHidden($form->get('idPabellon')); ?>
		<h4>Datos Personales</h4><hr>
		<div class="col-sm-2">
			<?php
    			$nombre = $form->get('nombre');
    			echo $formLabel->openTag() . $nombre->getLabel('label');    			
    			//echo $this->formElementErrors($nombre);
    			echo $formLabel->closeTag();
    			echo $this->formInput($nombre);
			?>
		</div>
	</div>
	<br>
	
	<div class="row">
		
		<div class="col-sm-12">
			<?php echo $this->formElement($form->get('send')) ?> 
		</div>		



	</div>

</div>





<?php  echo $this->form()->closeTag() ?>
