<script type="text/javascript">
    $(document).ready(function() {
        $('#botonBuscar').on('click', function() {
            //var banco= idBancoPorCliente.;
            var fechaIn= $('#fechaDesde').val();
            var fechaOut=$('#fechaHasta').val();
            if(fechaIn === "" || fechaOut === "") {
                alert('Ingrese un rango de Fechas');
                return false;
            } else if(fechaIn > fechaOut) {
                alert('La Fecha Hasta es mayor a la Fecha Desde, por favor modifique las Fechas');
                return false;
            } else {
                url = "gridreserva" + "/" + fechaIn + "/" + fechaOut;
                alert(url); 
                $(location).attr('href', url);
            }
        });
    });
</script>
<div class="container">
    <br>
    <ol class="breadcrumb">
        <li class="active">Reservas</li>

    </ol>
    <h4>Buscar por rango de fechas</h4><br>


    <div class="row">
        <div class="col-sm-2">
            <label for="fechaDesde">Fecha Desde:
                <input type="date" id="fechaDesde" class="form-control" placeholder="Ingresar fecha Desde">
            </label>
        </div>    
        <div class="col-sm-2">    
            <label for="fechaHasta">Fecha Hasta:
                <input type="date" id="fechaHasta" class="form-control" placeholder="Ingresar fecha Hasta">
            </label>    
        </div>
        <div class="col-sm-2">
            <a type="button" id="botonBuscar" class="btn btn-primary">Buscar</a>
        </div>
    </div>
    <h4><?php echo $this->translate('Reservas al '.$this->fecha); ?></h4>
    <?php foreach($this->getPabellones() as $pabellon): ?>
    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-info">
                <div class="panel-heading"><?php echo $pabellon->getNombre(); ?></div>
                <div class="panel-body">
                    <?php
                    /* @var \Reserva\Model\Habitacion $habitacion */
                    foreach($this->getHabitaciones($pabellon->getId()) as $habitacion): ?>
                        <a type="button"
                           style="color:black;"
                           class="btn <?php echo $this->getHabitacionStatus($habitacion, $this->fecha);?>"
                           href="<?php echo $this->getHabitacionHref($habitacion, $this->fecha) ?>"
                           title="<?php echo $this->getHabitacionTitle($habitacion, $this->fecha); ?>"
                            >
                            <?php echo $habitacion->getNumero(); ?>
                        </a>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
    <?php endforeach; ?>
</div>
