<script language="JavaScript">
    function doSearch() 
    {
        var tableReg = document.getElementById('datos');
        var searchText = document.getElementById('buscador').value.toLowerCase();
        for (var i = 1; i < tableReg.rows.length; i++)
        {
            var cellsOfRow = tableReg.rows[i].getElementsByTagName('td');
            var found = false;
            for (var j = 0; j < cellsOfRow.length && !found; j++)
            {
                var compareWith = cellsOfRow[j].innerHTML.toLowerCase();
                if (searchText.length == 0 || (compareWith.indexOf(searchText) > -1))
                {
                    found = true;
                }
            }
            if(found) 
            {
                tableReg.rows[i].style.display = '';
            }else{
                    tableReg.rows[i].style.display = 'none';
                 }
        }
    }    
</script>
<div class="container">
    <br>
    <ol class="breadcrumb">
        <li class="active">Tarifas</li>    
    </ol>
    <h3><?php echo $this->titulo ?></h3>
    <br>
    <!-- desde aca -->
    <div class="row">
        <div class="col-sm-3">
            <label for="buscador">Buscar Tarifa</label>
            <input type="text" onkeyup="doSearch()" id="buscador" class="form-control">
        </div>  
    </div>
    <br>
    <!-- hasta aca -->
    <a href="<?php echo $this->url('reserva', array('controller'=> 'reserva', 'action' => 'addtarifa')) ?>">Nuevo Tarifa (+)</a>
    <br><br>
    <table class="table" id="datos">
        <tr>
            <th>Categoria Habitacion</th>
            <th>Tipo de Convenio</th>
            <th>Monto Diario</th>
            <th>Vigencia</th>
            <th>Editar Tarifa</th>
            <th>Eliminar Tarifa</th>

        </tr>
        <?php foreach($tarifas as $tarifa) 
        {
        ?>
        
            <tr style="background-color:<?php echo $this->cycle(array("#F0F0F0","#FFFFFF"))->next() ?>">
            

                <td><?php echo $this->escapeHtml($this->getCategoriaName($tarifa->idCategoria));?></td>
                <td><?php echo $this->escapeHtml($this->getTipoHuespedName($tarifa->idTipoHuesped));?></td>
                <td>$<?php echo $this->escapeHtml($tarifa->monto);?></td>
                <td><?php echo $this->escapeHtml($tarifa->vigencia);?></td>
                <td>
                    <a href="<?php echo $this->url('reserva', array('controller'=> 'reserva', 'action' => 
                    'edittarifa', 'id' =>$tarifa->idTarifa)) ?>">Editar</a>
                </td>
                <td>
                    <a onclick="return confirm('Esta seguro que desea eliminar la tarifa <?php echo $tarifa->idTarifa ?>?')"
                    href="<?php echo $this->url('reserva', array('controller'=> 'reserva', 'action' => 'deletetarifa',
                    'id' => $tarifa->idTarifa)) ?>">Eliminar</a>
                </td>
            </tr>
        <?php
        }       
        ?>      
        <?php
            $this->cycle()->assign(array("#F0F0F0","#FFFFFF"));
            $this->cycle()->prev();
        ?>
        



    </table>

</div>






