<script language="JavaScript">
    function doSearch() 
    {
        var tableReg = document.getElementById('datos');
        var searchText = document.getElementById('buscador').value.toLowerCase();
        for (var i = 1; i < tableReg.rows.length; i++)
        {
            var cellsOfRow = tableReg.rows[i].getElementsByTagName('td');
            var found = false;
            for (var j = 0; j < cellsOfRow.length && !found; j++)
            {
                var compareWith = cellsOfRow[j].innerHTML.toLowerCase();
                if (searchText.length == 0 || (compareWith.indexOf(searchText) > -1))
                {
                    found = true;
                }
            }
            if(found) 
            {
                tableReg.rows[i].style.display = '';
            }else{
                    tableReg.rows[i].style.display = 'none';
                 }
        }
    }    
</script>

<div class="container">
    <br>
    <ol class="breadcrumb">
        <li class="active">Habitaciones</li>    
    </ol>
    <h3><?php echo $this->titulo ?></h3>
    <br>
 
    
    <!-- desde aca -->
    <div class="row">
        <div class="col-sm-3">
            <label for="buscador">Buscar Habitacion</label>
            <input type="text" onkeyup="doSearch()" id="buscador" class="form-control">
        </div>  
    </div>
    <br>
    <!-- hasta aca -->
    <a href="<?php echo $this->url('reserva', array('controller'=> 'reserva', 'action' => 'addhabitacion')) ?>">Nueva Habitacion (+)</a>
    <br><br>
    <table class="table" id="datos">
        <tr>
            <th>Numero</th>
            <th>Pabellon</th>
            <th>Plazas Maximas</th>
            <th>Categoria</th>
            <th>Editar Habitacion</th>
            <th>Eliminar Habitacion</th>

        </tr>
        <?php foreach($habitaciones as $habitacion) 
        {
        ?>
        
            <tr style="background-color:<?php echo $this->cycle(array("#F0F0F0","#FFFFFF"))->next() ?>">
            
                <td><?php echo $this->escapeHtml($habitacion->numero);?></td>
                <td><?php echo $this->escapeHtml($this->getPabellonName($habitacion->idPabellon));?></td>
                <td><?php echo $this->escapeHtml($habitacion->plazaMaxima);?></td>
                <td><?php echo $this->escapeHtml($this->getCategoriaName($habitacion->idCategoria));?></td>
                <td>
                    <a href="<?php echo $this->url('reserva', array('controller'=> 'reserva', 'action' => 
                    'edithabitacion', 'id' =>$habitacion->idHabitacion)) ?>">Editar</a>
                </td>
                <td>
                    <a onclick="return confirm('Esta seguro que desea eliminar la habitacion nro <?php echo $habitacion->numero?>?')" 
                    href="<?php echo $this->url('reserva', array('controller'=> 'reserva', 'action' => 'deletehabitacion', 
                    'id' => $habitacion->idHabitacion)) ?>">Eliminar</a>
                </td>
            </tr>
        <?php
        }       
        ?>      
        <?php
            $this->cycle()->assign(array("#F0F0F0","#FFFFFF"));
            $this->cycle()->prev();
        ?>
    </table>

</div>
