<?php
$records = array();
            foreach ($pabellones as $pabellon)
            {
                $records[] = $pabellon;
            }
?>            
<div class="container">
    <br>
    <ol class="breadcrumb">
        <li class="active">Reservas</li>

    </ol>
        <h4>Buscar por rango de fechas</h4><br>


    <div class="row">
        <div class="col-sm-2">
            <label for="fechaDesde">Fecha Desde:
                <input type="date" id="fechaDesde" class="form-control" placeholder="Ingresar fecha Desde">
            </label>
        </div>    
        <div class="col-sm-2">    
            <label for="fechaHasta">Fecha Hasta:
                <input type="date" id="fechaHasta" class="form-control" placeholder="Ingresar fecha Hasta">
            </label>    
        </div>
        <div class="col-sm-2">    
            <label for="pabellones">Pabellon:
            <select class="form-control" id="pabellones">
                <?php
                    foreach($records as $record)
                    {
                        ?>
                        <option value="<?php $record->idPabellon?>">
                            <?php echo $record->nombre ?>
                        </option>
                        <?php
                    }
                ?>    
            </select>
        </div>        
        <div class="col-sm-2">    <br><?php $hola=12 ?>
            <a type="button" class="btn btn-primary" href="<?php echo $this->url('reserva', array('controller'=> 'reserva', 'action' => 
                    'gridreserva', 'fechaDesde' => 3, 'fechaHasta' =>3,)) ?>">Buscar </a>
        </div>    


    </div>
    <br><br>

    <h4><?php echo $this->titulo;?></h4>
    <br>
    
            <?php
            $estado=0;
            $disponibles=array();
            foreach ($reservas as $reserva)
            {
                
                $disponibles[] = $reserva;
            };

            
            

                foreach($records as $record)
                {

                    ?>
                    <div class="row">
                    <div class="col-sm-12">
                        <div class="panel panel-info">
                                                          
                                <div class="panel-heading">
                                    <?php echo $record->nombre  ?>
                                </div>
                                
                                <div class="panel-body">
                                   
                                        <?php                  
                                            foreach($habitaciones as $habitacion)
                                            {   
                                                
                                                if($habitacion->idPabellon==$record->idPabellon)
                                                {
                                                    $estado=0;
                                                    foreach($disponibles as $disponible)
                                                    {
                                                        

                                                        if($habitacion->idHabitacion==$disponible["idHabitacion"])
                                                        {
                                                           $estado=$disponible["idEstado"];
                                                        }
                                                    }                                                    
                                                    ?>
                                                    <?php
                                                    switch ($estado) {
                                                        case '1':
                                                            $colorHabitacion="#2EFE2E";
                                                            break;
                                                        case '2':
                                                            $colorHabitacion="blue";
                                                            break;
                                                        case '3':
                                                            $colorHabitacion="yellow";
                                                            break;
                                                        default:
                                                            $colorHabitacion="#D8D8D8";
                                                            break;
                                                    }
                                                    ?>
                                                <a type="button" style="background-color:<?php echo $colorHabitacion;?>;color:black;" class="btn" href="<?php echo $this->url('reserva', array('controller'=> 'reserva', 'action' => 
                    'book', 'id' =>$habitacion->idHabitacion)) ?>"><?php echo $habitacion->numero; ?></a>
                                                    <?php

                                                }
                                                
                                            }

                                            
                                        ?>  
                                            

                                  
                                </div>
                           
                        </div>
                        </div>
                    </div>
                      
                    <?php
                }
            ?>

            
            
    <br>
    <br>
    <br>
</div>
