<div class="container"><?php
		$form = $this->form;
		$form->setAttribute('action', $this->url('pabellon', array('action' => 'edit', 'id' => $form->get('idPabellon')->getValue())));
    	$form->prepare();
		$formLabel = $this->plugin('formLabel');
		echo $this->form()->openTag($form);
	?>
	<ol class="breadcrumb">
  		<li><a href="<?php echo $this->url('pabellon')?>">Pabellones</a></li>
  		<li class="active">Edicion</li>  		
	</ol>
	<h3><?php echo $this->translate('Editar Pabellon') ?></h3>
	<div class="row">
		<?php echo $this->formHidden($form->get('idPabellon')); ?>
		<div class="col-sm-2">
			<?php
    			$nombre = $form->get('nombre');
    			echo $formLabel->openTag() . $nombre->getLabel('label') . $formLabel->closeTag();
			//echo $this->formElementErrors($nombre);
			echo $this->formInput($nombre);
			?>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-12">
			<?php echo $this->formElement($form->get('send')) ?> 
		</div>		
	</div>
	<?php  echo $this->form()->closeTag() ?>
</div>