
<div class="container">
	<?php
		$form = $this->form;
		$form->setAttribute('action', $this->url('proveedor', array('action' => 'add')));
    	$form->prepare();
		$formLabel = $this->plugin('formLabel');
		echo $this->form()->openTag($form);
	?>

	<br>
	<ol class="breadcrumb">
  		<li><a href="<?php echo $this->url('home')?>proveedor/index">Proveedores</a></li>
  		<li class="active">Alta</li>  		
	</ol>
	<h3><?php echo $this->titulo ?></h3>	
	<br>	
	<div class="row">
		<h4>Datos Proveedor</h4><hr>
		<div class="col-sm-2">
			<?php
    			$cuit = $form->get('cuit');
    			echo $formLabel->openTag() . $cuit->getLabel('label');    			
    			
    			echo $formLabel->closeTag();

    			echo $this->formInput($cuit);

    			
    				echo $this->formElementErrors($cuit);	
    			   			
    			
			?>
		</div>

		<div class="col-sm-2">
			<?php
    			$nombreCompania = $form->get('nombreCompania');
    			echo $formLabel->openTag() . $nombreCompania->getLabel('label');    			
    			//echo $this->formElementErrors($nombre);
    			echo $formLabel->closeTag();
    			echo $this->formInput($nombreCompania);
			?>
		</div>
		<div class="col-sm-2">
			<?php
    			$nombreContacto = $form->get('nombreContacto');
    			echo $formLabel->openTag() . $nombreContacto->getLabel('label');    			
    			//echo $this->formElementErrors($pass);
    			echo $formLabel->closeTag();
    			echo $this->formInput($nombreContacto);
			?>
		</div>
		
		<div class="col-sm-3">
			<?php
    			$telefonoFijo = $form->get('telefonoFijo');
    			echo $formLabel->openTag() . $telefonoFijo->getLabel('label');    			
    			//echo $this->formElementErrors($telFijo);
    			echo $formLabel->closeTag();
    			echo $this->formInput($telefonoFijo);
			?>
		</div>		
		<div class="col-sm-3">
			<?php
    			$telefonoCelular = $form->get('telefonoCelular');
    			echo $formLabel->openTag() . $telefonoCelular->getLabel('label');    			
    			//echo $this->formElementErrors($telCelular);
    			echo $formLabel->closeTag();
    			echo $this->formInput($telefonoCelular);
			?>
		</div>
	</div>
	<br>
	<div class="row">
		<div class="col-sm-2">
			<?php
    			$provincia = $form->get('provincia');
    			echo $formLabel->openTag() . $provincia->getLabel('label');    			    			
    			echo $formLabel->closeTag();
    			echo $this->formSelect($provincia);
    			//echo $this->formElementErrors($provincia);
			?>  			
		</div>
		<div class="col-sm-2">
			<?php
    			$localidad = $form->get('localidad');
    			echo $formLabel->openTag() . $localidad->getLabel('label');    			    			
    			echo $formLabel->closeTag();
    			echo $this->formInput($localidad);
    			//echo $this->formElementErrors($localidad);
			?>  			
		</div>
		<div class="col-sm-4">
			<?php
    			$email = $form->get('email');
    			echo $formLabel->openTag() . $email->getLabel('label');    			
    			//echo $this->formElementErrors($email);
    			echo $formLabel->closeTag();
    			echo $this->formInput($email);
			?>
		</div>
	</div>
	<br>
	<div class="row">
		
		<div class="col-sm-3">
			<?php
    			$direccion = $form->get('direccion');
    			echo $formLabel->openTag() . $direccion->getLabel('label');    			
    			//echo $this->formElementErrors($domicilio);
    			echo $formLabel->closeTag();
    			echo $this->formInput($direccion);
			?>
		</div>
		<div class="col-sm-2">
			<?php
    			$idCodigoPostal = $form->get('codigoPostal');
    			echo $formLabel->openTag() . $idCodigoPostal->getLabel('label');    			    			
    			echo $formLabel->closeTag();
    			echo $this->formInput($idCodigoPostal);
    			//echo $this->formElementErrors($documento);
			?>  			
		</div>		
	</div>
	<br>

	<br>	
	<div class="row">
		
		<div class="col-sm-12">
			<?php echo $this->formElement($form->get('send')) ?> 
		</div>		



	</div>

</div>





<?php  echo $this->form()->closeTag() ?>
