<script language="JavaScript">
    function doSearch() 
    {
        var tableReg = document.getElementById('datos');
        var searchText = document.getElementById('buscador').value.toLowerCase();
        for (var i = 1; i < tableReg.rows.length; i++)
        {
            var cellsOfRow = tableReg.rows[i].getElementsByTagName('td');
            var found = false;
            for (var j = 0; j < cellsOfRow.length && !found; j++)
            {
                var compareWith = cellsOfRow[j].innerHTML.toLowerCase();
                if (searchText.length == 0 || (compareWith.indexOf(searchText) > -1))
                {
                    found = true;
                }
            }
            if(found) 
            {
                tableReg.rows[i].style.display = '';
            }else{
                    tableReg.rows[i].style.display = 'none';
                 }
        }
    }    
</script>
<div class="container">
    <br>
    <ol class="breadcrumb">
        <li class="active">Proveedores</li>    
    </ol>
    <h3><?php echo $this->titulo ?></h3>
    <br>
    <!-- desde aca -->
    <div class="row">
        <div class="col-sm-3">
            <label for="buscador">Buscar Proveedor</label>
            <input type="text" onkeyup="doSearch()" id="buscador" class="form-control">
        </div>  
    </div>
    <br>
    <!-- hasta aca -->
    <a href="<?php echo $this->url('proveedor', array('controller'=> 'proveedor', 'action' => 'add')) ?>">Nuevo Proveedor (+)</a>
    <br><br>
    <table class="table" id="datos">
        <tr>
            <th>CUIT</th>
            <th>Nombre Compañia</th>
            <th>Nombre Contacto</th>
            <th>Telefono Celular</th>
            <th>Telefono Fijo</th>
            <th>Editar Proveedor</th>
            <th>Eliminar Proveedor</th>

        </tr>

        <?php 

        foreach($proveedores as $proveedor) 
        {
        ?>
        
            <tr style="background-color:<?php echo $this->cycle(array("#F0F0F0","#FFFFFF"))->next() ?>">
            
                <td><?php echo $this->escapeHtml($proveedor->cuit);?></td>
                <td><?php echo $this->escapeHtml($proveedor->nombreCompania );?></td>
                <td><?php echo $this->escapeHtml($proveedor->nombreContacto);?></td>
                <td><?php echo $this->escapeHtml($proveedor->telefonoCelular);?></td>
                <td><?php echo $this->escapeHtml($proveedor->telefonoFijo);?></td>
                <td>
                    <a href="<?php echo $this->url('proveedor', array('controller'=> 'proveedor', 'action' => 
                    'edit', 'id' =>$proveedor->idProveedor)) ?>">Editar</a>
                </td>
                <td>
                    <a onclick="return confirm('Esta seguro que desea eliminar a <?php echo $proveedor->cuit ?>?')" 
                    href="<?php echo $this->url('proveedor', array('controller'=> 'proveedor', 'action' => 'delete', 
                    'id' => $proveedor->idProveedor)) ?>">Eliminar</a>
                </td>
            </tr>
        <?php
        }       
        ?>      
        <?php
            $this->cycle()->assign(array("#F0F0F0","#FFFFFF"));
            $this->cycle()->prev();
        ?>
        



    </table>

</div>






