<?php echo $this->doctype(); ?>

<html lang="es">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Casa Serrana '. $this->translate(''))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/bellboy.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/jquery-ui.min.css')
                        ->prependStylesheet($this->basePath() . '/css/jquery-ui.structure.min.css')
                        ->prependStylesheet($this->basePath() . '/css/jquery-ui.theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>


        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/utils.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery-ui.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
       
    </head>
    <body>
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">         
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>">&nbsp;<?php echo $this->translate('Casa Serrana') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        
                        <li class="dropdown">
                            <a href="<?php echo $this->url('home') ?>" class="dropdown-toggle" data-toggle="dropdown">
                                <span class="glyphicon glyphicon-book"></span>
                                <?php echo $this->translate(' Reservas') ?>
                                <span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="<?php echo $this->url('reserva') ?>">Consultar Reserva</a></li>
                                    <li><a href="<?php echo $this->url('reserva', array( 'action' => 'add')) ?>">Nueva Reserva</a></li>
                                    <li><a href="<?php echo $this->url('habitacion') ?>">Habitaciones</a></li>
                                    <li><a href="<?php echo $this->url('pabellon') ?>">Pabellones</a></li>
                                    <li><a href="<?php echo $this->url('tarifa') ?>">Tarifas</a></li>
                                    <li><a href="<?php echo $this->url('tipo-convenio') ?>">Tipo Convenios</a></li>
                                </ul>
                            </a>
                        </li>
                        <li class="dropdown">
                            <a href="<?php echo $this->url('home') ?>" class="dropdown-toggle" data-toggle="dropdown">
                                <span class="glyphicon glyphicon-user"></span>
                                <?php echo $this->translate(' Clientes') ?>
                                <span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="<?php echo $this->url('facturascripts') ?>?page=ventas_clientes">Consulta Clientes</a></li>
                                    <li><a href="<?php echo $this->url('home') ?>cliente/add">Alta Cliente</a></li>
                                    <li><a href="<?php echo $this->url('home') ?>banco/index">Bancos</a></li>
                                    <li><a href="<?php echo $this->url('home') ?>tarjeta/index  ">Tarjetas</a></li>
                                    <li><a href="<?php echo $this->url('home') ?>alimento/index">Alimentos Especiales</a></li>
                                    <li><a href="<?php echo $this->url('facturascripts') ?>?page=ventas_facturas">Facturas a Clientes</a></li>
                                </ul>
                            </a>
                        </li>
                        <li>
                            <!--
                            <a href="<?php echo $this->url('home') ?>">
                                <span class="glyphicon glyphicon-glass"></span>
                                <?php echo $this->translate(' Bar') ?>
                            </a>
                            -->
                        </li>
                        <li class="dropdown">
                            <a href="<?php echo $this->url('facturascripts') ?>?page=admin_almacenes" class="dropdown-toggle" data-toggle="dropdown">
                                <span class="glyphicon glyphicon-th-large"></span>
                                <?php echo $this->translate(' Deposito') ?>
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="<?php echo $this->url('facturascripts') ?>?page=admin_almacenes">Almacenes</a></li>
                                <li><a href="<?php echo $this->url('facturascripts') ?>?page=almacenes_albaranes">Movimientos entre Almacenes</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="<?php echo $this->url('facturascripts') ?>?page=contabilidad_cuentas" class="dropdown-toggle" data-toggle="dropdown">
                                <span class="glyphicon glyphicon-usd"></span>
                                <?php echo $this->translate(' Tesoreria') ?>
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="<?php echo $this->url('facturascripts') ?>?page=contabilidad_ejercicios">Ejercicios</a></li>
                                <li><a href="<?php echo $this->url('facturascripts') ?>?page=contabilidad_asientos">Asientos</a></li>
                                <li><a href="<?php echo $this->url('facturascripts') ?>?page=tpv_caja">Cajas</a></li>
                                <li><a href="<?php echo $this->url('facturascripts') ?>?page=tpv_recambios">TPV Generico</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('facturascripts') ?>?page=contabilidad_cuentas">
                                <span class="glyphicon glyphicon-list-alt"></span>
                                <?php echo $this->translate(' Contaduria') ?>
                            </a>
                        </li>
                        <li class="dropdown">
                            <a href="<?php echo $this->url('facturascripts') ?>?page=compras_proveedores" class="dropdown-toggle" data-toggle="dropdown">
                                <span class="glyphicon glyphicon-barcode"></span>
                                Proveedores
                                <span class="caret"></span>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="<?php echo $this->url('facturascripts') ?>?page=compras_proveedores">Proveedores</a></li>
                                    <li><a href="<?php echo $this->url('facturascripts') ?>?page=ventas_articulos">Articulos</a></li>
                                    <li><a href="<?php echo $this->url('facturascripts') ?>?page=compras_albaranes">Compra a Proveedores</a></li>
                                </ul>
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('facturascripts') ?>">
                                <span class="glyphicon glyphicon-stats"></span>
                                Reportes
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('facturascripts') ?>">
                                <span class="glyphicon glyphicon-list-alt"></span>

                                <?php echo $this->translate(' Informes') ?>

                                Auditoria

                            </a>
                        </li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2014 - <?php echo date('Y') ?> by Cruzero Group <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
