<script type="text/javascript">
    function doSearch() {
        var tableReg = document.getElementById('datos');
        var searchText = document.getElementById('buscador').value.toLowerCase();
        for (var i = 1; i < tableReg.rows.length; i++) {
            var cellsOfRow = tableReg.rows[i].getElementsByTagName('td');
            var found = false;
            for (var j = 0; j < cellsOfRow.length && !found; j++) {
                var compareWith = cellsOfRow[j].innerHTML.toLowerCase();
                if (searchText.length == 0 || (compareWith.indexOf(searchText) > -1)) {
                    found = true;
                }
            }
            if(found) {
                tableReg.rows[i].style.display = '';
            } else {
                tableReg.rows[i].style.display = 'none';
            }
        }
    }    
</script>
<div class="container">
    <ol class="breadcrumb">
        <li class="active">Tarifas</li>    
    </ol>
    <h3><?php echo $this->translate('Listado de Tarifas') ?></h3>
    <div class="row">
        <div class="col-sm-3">
            <label for="buscador">Buscar Tarifa</label>
            <input type="text" onkeyup="doSearch()" id="buscador" class="form-control">
        </div>  
    </div>
    <a href="<?php echo $this->url('tarifa', array('action' => 'add')) ?>">Nueva Tarifa (+)</a>
    <table class="table" id="datos">
        <thead>
            <tr>
                <th>Categoria Habitacion</th>
                <th>Tipo de Convenio</th>
                <th>Monto Diario</th>
                <th>Vigencia</th>
                <th>Opciones</th>
            </tr>
        </thead>
        <tbody>
<?php foreach($tarifas as $tarifa):
    /** @var \Reserva\Model\Tarifa $tarifa */?>
        <tr style="background-color:<?php echo $this->cycle(array("#F0F0F0","#FFFFFF"))->next() ?>">
            <td><?php echo $this->escapeHtml($this->getCategoriaName($tarifa->getIdCategoria()));?></td>
            <td><?php echo $this->escapeHtml($this->getTipoHuespedName($tarifa->getIdTipoHuesped()));?></td>
            <td>$<?php echo $this->escapeHtml($tarifa->getMonto());?></td>
            <td><?php echo $this->escapeHtml($tarifa->getVigencia());?></td>
            <td>
                <a href="<?php echo $this->url('tarifa', array('action' => 'edit', 'id' => $tarifa->getId())) ?>">
                    <span class="glyphicon glyphicon-pencil"></span>
                </a>
                &nbsp;
                <a onclick="return confirm('Esta seguro que desea eliminar la tarifa <?php echo $tarifa->getId() ?>?')"
                href="<?php echo $this->url('tarifa', array('action' => 'delete', 'id' => $tarifa->getId())) ?>">
                    <span class="glyphicon glyphicon-trash"></span>
                </a>
            </td>
        </tr>
<?php endforeach; ?>
        </tbody>
    </table>

</div>






