
<div class="container"><?php
		$form = $this->form;
		$form->setAttribute('action', $this->url('habitacion', array('action' => 'edit', 'id' => $form->get('idHabitacion')->getValue())));
    	$form->prepare();
		$formLabel = $this->plugin('formLabel');
		echo $this->form()->openTag($form);
	?>
	<ol class="breadcrumb">
  		<li><a href="<?php echo $this->url('habitacion')?>">Habitacion</a></li>
  		<li class="active">Edicion</li>  		
	</ol>
	<h3><?php echo $this->translate('Editar Habitacion') ?></h3>
	<div class="row">
		<h4>Datos habitacion</h4><hr>
		<?php echo $this->formHidden($form->get('idHabitacion')); ?>
		<div class="col-sm-2"><?php
			$numeroHabitacion = $form->get('numero');
			echo $formLabel->openTag() . $numeroHabitacion->getLabel('label') . $formLabel->closeTag();
			echo $this->formInput($numeroHabitacion);
			$habitacionErrors = $this->formElementErrors($numeroHabitacion);
			if($habitacionErrors):?>
				<div class="alert alert-warning" role="alert">
					<?php echo $habitacionErrors;?>
				</div>
			<?php endif; ?>
		</div>
		<div class="col-sm-2"><?php
			$idPabellon = $form->get('idPabellon');
			echo $formLabel->openTag() . $idPabellon->getLabel('label') . $formLabel->closeTag();
			echo $this->formSelect($idPabellon);
			$pabellonErrors = $this->formElementErrors($idPabellon);
			if($pabellonErrors):?>
				<div class="alert alert-warning" role="alert">
					<?php echo $pabellonErrors;?>
				</div>
			<?php endif; ?>
		</div>
		<div class="col-sm-2"><?php
			$plazaMaxima = $form->get('plazaMaxima');
			echo $formLabel->openTag() . $plazaMaxima->getLabel('label') . $formLabel->closeTag();
			echo $this->formInput($plazaMaxima);
			$plzMaxError = $this->formElementErrors($plazaMaxima);
			if($plzMaxError): ?>
				<div class="alert alert-warning" role="alert">
					<?php echo $plzMaxError;?>
				</div>
			<?php endif; ?>
		</div>
		<div class="col-sm-3"><?php
			$idCategoria = $form->get('idCategoria');
			echo $formLabel->openTag() . $idCategoria->getLabel('label');
			echo $formLabel->closeTag();
			echo $this->formSelect($idCategoria);
			$categoriaErrors = $this->formElementErrors($idCategoria);
			if($categoriaErrors):?>
				<div class="alert alert-warning" role="alert">
					<?php echo $categoriaErrors;?>
				</div>
			<?php endif; ?>
		</div>
		<div class="col-sm-3"><?php
			$idEstado = $form->get('idEstado');
			echo $formLabel->openTag() . $idEstado->getLabel('label');
			echo $formLabel->closeTag();
			echo $this->formSelect($idEstado);
			$estadoErrors = $this->formElementErrors($idEstado);
			if($estadoErrors):?>
				<div class="alert alert-warning" role="alert">
					<?php echo $estadoErrors;?>
				</div>
			<?php endif; ?>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-12">
			<?php echo $this->formElement($form->get('send')) ?>
		</div>
	</div>
	<?php  echo $this->form()->closeTag() ?>
</div>
