<div class="container"><?php
		$form = $this->form;
		$form->setAttribute('action', $this->url('tipo-convenio', array('action' => 'edit', 'id' => $form->get('idTipoHuesped')->getValue())));
    	$form->prepare();
		$formLabel = $this->plugin('formLabel');
		echo $this->form()->openTag($form);
	?>
	<ol class="breadcrumb">
  		<li><a href="<?php echo $this->url('tipo-convenio')?>">Tipos de Convenio</a></li>
  		<li class="active">Edicion</li>  		
	</ol>
	<h3><?php echo $this->translate('Editar Tipo de Convenio') ?></h3>
	<br>	
	<div class="row">
		<?php echo $this->formHidden($form->get('idTipoHuesped')); ?>
		<div class="col-sm-2">
			<?php
    			$nombre = $form->get('nombre');
    			echo $formLabel->openTag() . $nombre->getLabel('label');    			
    			//echo $this->formElementErrors($nombre);
    			echo $formLabel->closeTag();
    			echo $this->formInput($nombre);
			?>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-12">
			<?php echo $this->formElement($form->get('send')) ?> 
		</div>		
	</div>
	<?php  echo $this->form()->closeTag() ?>
</div>
