<script type="text/javascript">

    $(document).ready(function()
    {
        var numTarjeta=0;
        $('#agregarTarjeta').on('click', function()
        {
            numTarjeta= numTarjeta +1;
            //alert(numTarjeta);
            //var banco= idBancoPorCliente.;
            if(numTarjeta==3 || numTarjeta>3)
            {   
                alert('No se puede agregar mas de 3 tarjetas');
                return false;
            }
            
            $('#tarjetas').clone()
                    .attr('id', 'tarjetas')
                    //.attr('id', 'tarjetas')
                    .appendTo('.boxTarjeta')
            ;
            
            
        });
        
        $('#eliminarTarjeta').on('click', function()
        {
            if(numTarjeta === 0)
            {
                alert("No puede eliminar mas tarjetas");
                return false;
            }
            numTarjeta= numTarjeta - 1;
            //alert(numTarjeta);
            //var ultimo= $("#tarjetas:last");
            var ultimo= $("#tarjetas:last-child");
            //alert(ultimo);
            $( ultimo ).remove();
            
            
        });
    });

</script>
<div class="container">
	<?php
		$form = $this->form;
		$form->setAttribute('action', $this->url('cliente', array('action' => 'add')));
    	$form->prepare();
		$formLabel = $this->plugin('formLabel');
		echo $this->form()->openTag($form);
	?>

	<br>
	<ol class="breadcrumb">
  		<li><a href="<?php echo $this->url('home')?>cliente/index">Clientes</a></li>
  		<li class="active">Alta</li>  		
	</ol>
	<h3><?php echo $this->titulo ?></h3>	
	<br>	
	<div class="row">
		<?php echo $this->formHidden($form->get('idCliente')); ?>
		<h4>Datos Personales</h4><hr>
		<div class="col-sm-2">
			<?php
    			$apellido = $form->get('apellido');
    			echo $formLabel->openTag() . $apellido->getLabel('label');    			
    			
    			echo $formLabel->closeTag();
    			echo $this->formInput($apellido);
                        
			?>
                        <div style="color:red">
                            <?php echo $this->formElementErrors($apellido); ?>
                        </div>
                          
                        
		</div>
		<div class="col-sm-2">
			<?php
    			$nombre = $form->get('nombre');
    			echo $formLabel->openTag() . $nombre->getLabel('label');    			
    			echo $formLabel->closeTag();
    			echo $this->formInput($nombre);
			?>
                        <div style="color:red">
                            <?php echo $this->formElementErrors($nombre); ?>
                        </div>
		</div>
		<div class="col-sm-2">
			<?php
    			$fechaNacimiento = $form->get('fechaNacimiento');
    			echo $formLabel->openTag() . $fechaNacimiento->getLabel('label');    			
    			//echo $this->formElementErrors($pass);
    			echo $formLabel->closeTag();
    			echo $this->formInput($fechaNacimiento);
			?>
		</div>
		
		<div class="col-sm-3">
			<?php
    			$telefono = $form->get('telefono');
    			echo $formLabel->openTag() . $telefono->getLabel('label');
    			echo $formLabel->closeTag();
    			echo $this->formInput($telefono);
                        ?>
                        <div style="color:red">
                            <?php echo $this->formElementErrors($telefono); ?>
                        </div>
		</div>
	</div>
	<br>
	<div class="row">
		<div class="col-sm-2">
			<?php
    			$tipoDocumento = $form->get('tipoDocumento');
    			echo $formLabel->openTag() . $tipoDocumento->getLabel('label');    			    			
    			echo $formLabel->closeTag();
    			echo $this->formSelect($tipoDocumento);
    			echo $this->formElementErrors($tipoDocumento);
			?>  			
		</div>
		<div class="col-sm-2">
			<?php
    			$documento = $form->get('documento');
    			echo $formLabel->openTag() . $documento->getLabel('label');    			    			
    			echo $formLabel->closeTag();
    			echo $this->formInput($documento);
                         ?>
                        <div style="color:red">
                            <?php echo $this->formElementErrors($documento); ?>
                        </div>
		</div>
		<div class="col-sm-4">
			<?php
    			$email = $form->get('email');
    			echo $formLabel->openTag() . $email->getLabel('label');    			
    			//echo $this->formElementErrors($email);
    			echo $formLabel->closeTag();
    			echo $this->formInput($email);
			?>
		</div>
	</div>
	<br><br>
	<div class="row">
		<h4>Datos Residenciales</h4><hr>
		<div class="col-sm-3">
			<?php
    			$direccion = $form->get('direccion');
    			echo $formLabel->openTag() . $direccion->getLabel('label');    			
    			//echo $this->formElementErrors($direccion);
    			echo $formLabel->closeTag();
    			echo $this->formInput($direccion);
			?>
		</div>
		<div class="col-sm-3">
			<?php
    			$ciudad = $form->get('ciudad');
    			echo $formLabel->openTag() . $ciudad->getLabel('label');    			
    			//echo $this->formElementErrors($direccion);
    			echo $formLabel->closeTag();
    			echo $this->formInput($ciudad);
			?>
		</div>
		<div class="col-sm-2">
			<?php
    			$idCodigoPostal = $form->get('codigoPostal');
    			echo $formLabel->openTag() . $idCodigoPostal->getLabel('label');    			    			
    			echo $formLabel->closeTag();
    			echo $this->formInput($idCodigoPostal);
    			//echo $this->formElementErrors($documento);
			?>  			
		</div>
		<div class="col-sm-2">
			<?php				
    			$provincia = $form->get('provincia');
    			echo $formLabel->openTag() . $provincia->getLabel('label');
    			echo $formLabel->closeTag(); 
    			echo $this->formSelect($provincia);
    			?>
    			<div style="color:red">

    				<?php echo $this->formElementErrors($provincia);?>
    			</div>	
		</div>                
		<div class="col-sm-2">
			<?php
				
    			$pais = $form->get('pais');
    			echo $formLabel->openTag() . $pais->getLabel('label');
    			echo $formLabel->closeTag(); 
    			echo $this->formSelect($pais);
    			?>
    			<div style="color:red">

    				<?php echo $this->formElementErrors($pais);?>
    			</div>	
		</div>

	</div>
	<br><br>
	<div class="row">
		<h4>Datos Administrativos</h4><hr>
		<div class="col-sm-2">
			<div class="checkbox">
				<?php
					$titular = $form->get('titular');
    				echo $formLabel->openTag() . $titular->getLabel('label');    			    			
    				echo $formLabel->closeTag();
    				echo $this->formCheckbox($titular);
    			//	echo $this->formElementErrors($titular);
    			?>			
    		</div>
		</div>
		<div class="col-sm-2">
			<?php
    			$idBancoPorCliente = $form->get('idBancoPorCliente');
    			echo $formLabel->openTag() . $idBancoPorCliente->getLabel('label');    			    			
    			echo $formLabel->closeTag();
    			echo $this->formInput($idBancoPorCliente);
    			echo $this->formElementErrors($idBancoPorCliente);
			?>  			
		</div>
		
		<div class="col-sm-3">
			<?php
                            $alimento = $form->get('alimento');
                            echo $formLabel->openTag() . $alimento->getLabel('label');
                            echo $formLabel->closeTag(); 
                            echo $this->formSelect($alimento);
                            echo $this->formElementErrors($alimento);
			?>  			
		</div>
		
		
		
		<div class="col-sm-3">
			<?php
    			$idPadronAfiliado = $form->get('idPadronAfiliado');
    			echo $formLabel->openTag() . $idPadronAfiliado->getLabel('label');    			    			
    			echo $formLabel->closeTag();
    			echo $this->formSelect($idPadronAfiliado);
    		        echo $this->formElementErrors($idPadronAfiliado);
			?>  			
		</div>
	</div>	
        <br>

        <div class="boxTarjeta">
            
            <div class="row" id="tarjetas">
                <br>
			<div class="col-sm-2" >
				<?php
    				$idTarjetaPorCliente = $form->get('idTarjetaPorCliente');
    				echo $formLabel->openTag() . $idTarjetaPorCliente->getLabel('label');    			    			
    				echo $formLabel->closeTag();
    				echo $this->formInput($idTarjetaPorCliente);
    				//echo $this->formElementErrors($documento);
				?>  			
			</div>
                        <div class="col-sm-2">
                                <?php				
                                $tarjeta = $form->get('tarjeta');
                                echo $formLabel->openTag() . $tarjeta->getLabel('label');
                                echo $formLabel->closeTag(); 
                                echo $this->formSelect($tarjeta);
                                ?>
                        </div>
                        
                
            </div>                
        </div>
        <br><br>
            <input type="button" id="agregarTarjeta" class="btn btn-info" value="Agregar Tarjeta">
            <input type="button" id="eliminarTarjeta" class="btn btn-info" value="Eliminar Tarjeta">
        <br>
        </div><br>
	<?php
		if ($this->validaciones) {
			echo $this->validaciones;			
		}
	?>
	<br>	
	<div class="row">
		
		<div class="col-sm-12">
			<?php echo $this->formElement($form->get('send')) ?> 
		</div>		



	</div>

</div>





<?php  echo $this->form()->closeTag() ?>
